spring:
  application:
    name: ribbon-demo

server:
  port: 8951

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://server8761.com:8761/eureka

#hello-service:
#  ribbon:
#    ConnectTimeout: 5000 #服务请求连接超时时间（毫秒）
#    ReadTimeout: 5000 #服务请求处理超时时间（毫秒）
#    OkToRetryOnAllOperations: true #对超时请求启用重试机制
#    MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
#    MaxAutoRetries: 1 # 切换实例后重试最大次数
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改负载均衡算法
