server:
  port: 8954

spring:
  application:
    name: gateway-case
  cloud:
    gateway:
      routes:
        - id: hello-gateway
          uri: http://localhost:8801
          predicates:
            - Path=/hello/**
eureka:
  instance:
    hostname: gateway-case
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

