server:
  port: 8954

spring:
  application:
    name: gateway-case
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hello-gateway
#          uri: http://localhost:8801
          uri: lb://HELLO-SERVICE
          predicates:
            - Path=/hello/**
eureka:
  instance:
    hostname: gateway-case
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

